### ISSUE TITLE
Engineering

### ISSUE THREAD

**Issue by BadWorksFun** [benloz10/finalfrontier#2]
Sometimes Engineering won't work and when you select a action... it saids select action and then keeps both doors open + makes the sound. and doesn't splice etc.

**Comment by BadWorksFun** [comment]
Also For some reason it has 0 power even though is in perfect shape.

**Comment by BadWorksFun** [comment]
also sometimes some of the consoles stay blank as the Power, Shield, and Lifesupport when activating

**Comment by BadWorksFun** [comment]
I also get this error in my console.

![capture](https://user-images.githubusercontent.com/24305704/27823450-23bfdfcc-6077-11e7-8bfd-1de0c53cb199.JPG)

**Comment by ignis-quark** [comment]
A rework of some of the code and discovery of various possible causes of this will require further observation. This bug is possibly fixed, but I will require more up-to-date information with the new changes to be able to locate the issues. The "GetPlyOxygen" bug has been fixed.
